name: mobile_news_with_bloc
description: "Mobile news with bloc"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  auto_route: ^7.9.0
  get_it: ^7.6.7
  injectable: ^2.3.5
  injectable_generator: ^2.5.1
  auto_route_generator: ^7.3.2
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  logger: ^2.1.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_gen_runner: ^5.4.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/localization/
    - assets/images/
flutter_gen:
  output: lib/core/gen/assets/
  integrations:
    flutter_svg: true